name: deploy-mlflow-fastapi

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: deploy-mlflow-fastapi-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cleanup previous deployment
        run: |
          docker compose -f docker-compose.yml down -v --remove-orphans
          docker network prune -f

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build images
        run: docker compose -f docker-compose.yml build

      - name: Start infrastructure
        run: docker compose -f docker-compose.yml up -d postgres mlflow

      - name: Wait for services
        uses: docker/setup-buildx-action@v3
        with:
          wait-for-services: true
          wait-for-services-timeout: 300

      - name: Verify MLflow is running
        run: |
          timeout 120 bash -c 'until curl -f http://localhost:5000/api/2.0/mlflow/experiments/list; do sleep 5; done'

      - name: Train model
        run: docker compose -f docker-compose.yml run --rm trainer

      - name: Deploy API
        run: docker compose -f docker-compose.yml up -d serve

      - name: Verify FastAPI is running
        run: |
          timeout 60 bash -c 'until curl -f http://localhost:8000/health; do sleep 3; done'

      - name: Export logs
        if: always()
        run: docker compose -f docker-compose.yml logs --no-color > compose.log

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: compose-logs
          path: compose.log











