name: deploy-mlflow-fastapi

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: deploy-mlflow-fastapi-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        shell: powershell

    steps:
      - uses: actions/checkout@v4

      - name: Build images
        run: |
          docker compose -f docker-compose.yml build

      - name: Recreate MLflow and wait for API   # ✅ correctif minimal anti-503
        run: |
          docker compose -f docker-compose.yml rm -sf mlflow
          docker compose -f docker-compose.yml up -d mlflow

          # Attendre l’API /api/2.0 jusqu’à 10 minutes
          $deadline = (Get-Date).AddMinutes(10)
          $ok = $false
          $api = "http://127.0.0.1:5000/api/2.0/mlflow/experiments/list"

          do {
            $state = ""
            try { $state = (docker inspect -f '{{.State.Status}}' mlflow).Trim() } catch {}
            if ($state -eq "exited" -or $state -eq "dead") {
              Write-Host "=== mlflow logs (tail) ==="
              docker logs mlflow --tail 200
              throw "mlflow container exited (state=$state)"
            }
            try {
              Invoke-WebRequest -UseBasicParsing -Uri $api -TimeoutSec 5 | Out-Null
              $ok = $true
            } catch {
              Start-Sleep -Seconds 3
            }



