name: deploy-mlflow-fastapi

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: deploy-mlflow-fastapi-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cleanup previous deployment
        run: |
          docker compose -f docker-compose.yml down -v --remove-orphans
          docker network prune -f
          docker system prune -f

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build images
        run: docker compose -f docker-compose.yml build

      - name: Start infrastructure
        run: docker compose -f docker-compose.yml up -d postgres mlflow

      - name: Wait for MLflow UI
        uses: nev7n/wait_for_http_action@v1
        with:
          url: http://localhost:5000/
          maxAttempts: 30
          retryDelay: 5000

      - name: Wait for MLflow API
        uses: nev7n/wait_for_http_action@v1
        with:
          url: http://localhost:5000/api/2.0/mlflow/experiments/list
          maxAttempts: 30
          retryDelay: 5000

      - name: Train model
        run: docker compose -f docker-compose.yml run --rm trainer

      - name: Deploy API
        run: docker compose -f docker-compose.yml up -d serve

      - name: Wait for FastAPI
        uses: nev7n/wait_for_http_action@v1
        with:
          url: http://localhost:8000/health
          maxAttempts: 20
          retryDelay: 3000

      - name: Export logs
        if: always()
        run: docker compose -f docker-compose.yml logs --no-color > compose.log

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: compose-logs
          path: compose.log











